### PR TITLE
Fix translation capitalization on make request page

### PR DESCRIPTION
**Pull request by pajowu**
- refactor: minor alterations
- 🌐 Update translation files

### CODE REVIEW

**Comment by tyliec** [comment]
I'm still seeing this on the request page:

Screenshot 2024-05-06 at 11 31 20 AM

Do I need to do something more than a re-pull and `yarn build` / `yarn run serve` to see these changes?

**Comment by pajowu** [comment]
Did you run `django-admin compilemessages`?

**Comment by tyliec** [comment]
I just tried and I'm still seeing the same as the above after - the command seems to complete successfully:

```
➜  uipa git:(main) django-admin compilemessages
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide_campaign/froide_campaign/locale/en/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide_campaign/froide_campaign/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/da_DK/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/pt/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/fi_FI/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/de_AT/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/zh_CN/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/zh_HK/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/sv_SE/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide/locale/sv_FI/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide_payment/froide_payment/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/da_DK/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/pt/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/fi_FI/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/de_AT/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/zh_CN/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/zh_HK/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/sv_SE/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/froide/locale/sv_FI/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide_legalaction/froide_legalaction/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/froide_exam/froide_exam/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/node_modules/@okfde/filingcabinet/src/filingcabinet/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/Users/tylerchong/Desktop/workspace/codewithaloha/uipa/src/django-filingcabinet/src/filingcabinet/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
➜  uipa git:(main) echo $?
0
```

Noting that I'm seeing the capitalization changes from this PR being merged in, but not the internationalization change.

Screenshot 2024-05-06 at 1 05 17 PM

**Comment by pajowu** [comment]
Interesting, I can't reproduce this with the current main branch of froide 
Screenshot 2024-05-07 at 15 09 17

**Pull request merged**
