### PR TITLE
✨ Add setting to change project of a request

### PR DESCRIPTION
**Pull request by pajowu**
**Note**: This contains a lot of similar code to the 'Add team to project' feature.

### CODE REVIEW

**Comment by stefanw** [comment]
LGTM! I wouldn't worry about the duplication until the third time. And even then if it's more explicit and easier to follow some duplication can have benefits.

We don't have a good flow for working with translations, but generally I would only generate translations for our immediate use case. There is `make messagesde` which does some ignores and limits translation files to `de`. This keeps the PR smaller. Generating all translation files can be done for a proper release.

**Review by stefanw — APPROVED** [review]

**Review by stefanw — CHANGES_REQUESTED** [review]
We should probably hide the form when the person has no projects to choose from (does not look like that's happening?). Currently majority of user cannot create projects and for them this form is not relevant.

**Review by MagdaN — COMMENTED** [review]
Looks good and works nicely, the only problem I found is that when one of the options in the select field gets too long, the select field breaks the design.

**Comment by pajowu** [comment]
I added a check if at least one project can be selected in the form, otherwise the setting is not shown

**Review by stefanw — APPROVED** [review]

**Pull request merged**
